export const REFERENCE_SHOT_GRAMMAR: any;
export const ACTION_HINTS: readonly string[];
export const SHOT_SCALES: readonly string[];
export const SHOT_SILHOUETTES: readonly string[];
export const STORY_ROLES: readonly string[];
export const ASSET_STRATEGIES: readonly string[];
export function detectVisualVerb(text: string): string | null;
export function resolveVisualStrategy(clause: string, role?: string): any;
export function validateShotPlan(shots: any[], totalDurationSec?: any): any;
export function buildShotGrammarMetrics(shots: any[], totalDurationSec?: any): any;
export function evaluateAssetReuse(shot: any, asset: any): any;
export function resolveAssetStrategy(shot: any, approvedAssets?: any[]): any;
export function buildImagePromptForShot(shot: any, castContext?: any): string;
export function repairScaleMonotony(shots: any[]): any[];
export function isValidHoldException(shot: any): boolean;
export function chooseCompositionForShot(scale?: any, silhouette?: any, role?: any): any;
export function buildImageSafetyRulesForShot(shot?: any): string[];
export function mapPlannerScaleToRendererScale(options?: any): string;
export function choosePlannerScale(options?: any): any;
export function isSilhouetteCompatibleWithPeopleContract(silhouette: string, contract: any): boolean;
export const VISUAL_MODES: readonly string[];
export const VISUAL_MODE_TO_SCALE: Record<string, string>;
export function deriveVisualMode(options?: any): string;
export function validateActionPromptContract(options?: any): any;
export function validateVisibleRoleContract(options?: any): any;
export function validateFinalImagePromptContract(options?: any): any;
export function validateObjectDetailContract(options?: any): any;
